### PR TITLE
path.existsSync -> fs.existsSync

### PR DESCRIPTION
**Pull request by Rob--W**
`path.existsSync` is deprecated in favour of `fs.existsSync`.

### CODE REVIEW

**Comment by Rob--W** [comment]
Added another commit unrelated to the original issue. It allows me to change the display size.

**Comment by michel-kraemer** [comment]
Hey!

I like this package a lot. It really works well. The only thing that bugs me is the warning message that node prints out due to the use of deprecated api. It would be great if this PR could be merged and a new version published.

Thanks a lot!
Michel

**Comment by arnauorriols** [comment]
In node 0.12.0 path.existsSync has disappeared. It would be great if this pull request could be merged, otherwise the package can't be used in node 0.12.0

**Comment by Krinkle** [comment]
@Rob--W As a general best practice, I'd recommend creating topic branches (either separate from master or pointing to a commit within your master's history) so that the pull request doesn't include unrelated commits.

**Comment by Rob--W** [comment]
@Krinkle The second commit was required for my use case, I had to pass extra options. If the maintainer of this repo feels that only the other commit is necessary, they're free to cherry-pick the first commit and omit the second one.

**Comment by michel-kraemer** [comment]
@Rob--W I tested your fork and it works pretty well (even under node 0.12). Since the original author doesn't seem to maintain this package anymore, how about uploading your version under a new name (xvfb2) to the npm registry? Or maybe you can contact the npm guys and ask them if you could be added as a maintainer to the xvfb package. WDYT?

Cheers,
Michel

**Comment by Rob--W** [comment]
@michel-kraemer Is it even possible to take ownership of a package without the owner's consent? If not, then publishing as xvfb2 wouldn't be a terrible idea. Meanwhile, you can include a specific version of my (tag-less) fork by the hash, e.g. as done here: https://github.com/CodeYellowBV/run-headless-chromium/blob/6f9839387334b60b65325e61d0185b958bf03e16/package.json

**Comment by michel-kraemer** [comment]
Yes, I just did that. Works fine.

You may contact the author by mail if he doesn't read this thread. I usually prefer to contribute to existing projects instead of starting new ones but since the last change was in 2012... Let's see if he answers.

**Comment by Rob--W** [comment]
I am now the new maintainer of xvfb, and have just published the latest version (with my patches) as [xvfb@0.2.1](https://github.com/Rob--W/node-xvfb/releases/tag/0.2.1).

It is fully backwards-compatible with 0.2.1, except when xvfb is not installed. In 0.2.0, Node would terminate because the spawn failure triggered an uncatcheable error. In 0.2.1, the library catches the error and passes the error to the callback (https://github.com/Rob--W/node-xvfb/commit/1c518a9ab06d8e558659bcc3689f6ed8e0e38642).

**Comment by michel-kraemer** [comment]
Great. Thank you so much!

**Pull request closed without merging**
